# Stochastic local search algorithm techniques in R for the N-queens problem

https://cran.r-project.org/web/packages/NMOF/vignettes/LSqueens.pdf

### Install package 

In [1]:
install.packages('NMOF')

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


### Load library

In [2]:
library('NMOF')

### Set seed value for random

In [3]:
set.seed(1345797)

### Set N values for size of chess board and number of queens

In [4]:
N <- 8

### Create random position for row at which initialy queens are placed.

In [5]:
rand_position <- sample.int(N)

rand_position

[1] 6 5 7 2 3 8 1 4

### Make a data frame for with rows and position of queens

In [6]:
data_frame <- data.frame(row = 1:N, column = rand_position)

data_frame

row column
1 1   6     
2 2   5     
3 3   7     
4 4   2     
5 5   3     
6 6   8     
7 7   1     
8 8   4

### Create a chess board of N x N at which queens are placed at random position 

Note:- 
* `seq_len(n) give us sequence number till the value of n. `


* `rep('-', n)` gives us n numbers of `-` in a row.

like:- seq_len(8) = `1 2 3 4 5 6 7 8`

In [7]:
chessboard <- function(rand_position, queen = "Q", sep = '  ') {
    n <- length(rand_position)
    row <- rep('_', n)

    for (i in seq_len(n)) {
        row_i <- row
        row_i[rand_position[i]] <- queen
        
        cat(paste(row_i, collapse = sep))
        cat('\n')
    }
}

In [8]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


### Create a matrix of N x N  with `NA` values and labeled to detect where queens are present

In [9]:
matrix_diag <- array(NA, dim = c(N, N))

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

In [12]:
for (row in 1:N)
    for (col in 1:N)
        matrix_diag[row, col] <- col - row
    
matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

### Create another matrix of N x N  with `NA` values and labeled for reverse diagonal, to detect where queens are present

In [13]:
matrix_rev_diag <- array(NA, dim = c(N, N))

matrix_rev_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

### Matrix with reverse diagonal

In [15]:
for (row in 1:N)
    for (col in 1:N)
        matrix_rev_diag[row, col] <- col + row - (N + 1)

matrix_rev_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] -7   -6   -5   -4   -3   -2   -1   0   
[2,] -6   -5   -4   -3   -2   -1    0   1   
[3,] -5   -4   -3   -2   -1    0    1   2   
[4,] -4   -3   -2   -1    0    1    2   3   
[5,] -3   -2   -1    0    1    2    3   4   
[6,] -2   -1    0    1    2    3    4   5   
[7,] -1    0    1    2    3    4    5   6   
[8,]  0    1    2    3    4    5    6   7

### calculate row wise attacks  i.e more than one `Q`

In [29]:
rand_position

[1] 6 5 7 2 3 8 1 4

In [30]:
duplicated(rand_position)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [31]:
sum(duplicated(rand_position))

[1] 0

### Calculate diagonal wise attack i.e more than one `Q`

In [32]:
duplicated(rand_position - seq_along(rand_position))

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [33]:
rand_position - seq_along(rand_position)

[1]  5  3  4 -2 -2  2 -6 -4

In [34]:
sum(duplicated(rand_position - seq_along(rand_position)))

[1] 1

### Calculate reverse diagonal wise attack i.e more than one `Q`

In [35]:
duplicated(rand_position + seq_along(rand_position))

[1] FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

In [36]:
rand_position + seq_along(rand_position)

[1]  7  7 10  6  8 14  8 12

In [37]:
sum(duplicated(rand_position + seq_along(rand_position)))

[1] 2

### Calculate over all attack when we placed queen randomly

In [40]:
num_attacks <- function(rand_position) {
    sum(duplicated(rand_position)) + 
    sum(duplicated(rand_position - seq_along(rand_position))) + 
    sum(duplicated(rand_position + seq_along(rand_position)))
}

In [41]:
num_attacks(rand_position)

[1] 3

### Create a neighbour function to shift `queen`  according to given step values if two `queens` are attacks.

Note:- 
* In this condition if two queens are attacks row wise, column wise or diagonaly then one of them shift by step value, and if at extream left then shifted to extream right of row and vice versa.

* Here, step value can between 1 to N value.

In [43]:
move_one_queen <- function(rand_position){
    step <- 4
    i <- sample.int(N, 1)
    
    rand_position[i] <- rand_position[i] + sample(c(1:step, -(1:step)), 1)
    
    if (rand_position[i] > N)
        rand_position[i] <- 1
    else if (rand_position[i] < 1)
        rand_position[i] <- N
    
    rand_position
}

### Initial chess board

In [44]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


### In above chess board, quees are attacks, so we call to neighbour function to shift queens so that finaly number of attack will be zero.
* First call

In [45]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


* Second call

In [46]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


* Third call

In [47]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
Q  _  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


### Create another position of chess so that each queen lies on first position of each row.

In [48]:
p0 <- rep(2, N)

p0

[1] 2 2 2 2 2 2 2 2

### Create a chess board, in which each queen has position is one. 

In [52]:
chessboard(p0)

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _


In [53]:
chessboard(rand_position <- move_one_queen(p0))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  Q  _  _  _


In [54]:
chessboard(rand_position <- move_one_queen(rand_position))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


### Stochastic Local Search

In [55]:
stochastic_local_search <- LSopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                 printBar = T, nS = 10000))


Local Search.
Initial solution:  7 
  |======================================================================| 100%
Finished.
Best solution overall: 0


In [56]:
stochastic_local_search$xbest

[1] 4 6 8 2 7 1 3 5

### Visualization of chess board

In [57]:
chessboard(stochastic_local_search$xbest)

_  _  _  Q  _  _  _  _
_  _  _  _  _  Q  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
Q  _  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  Q  _  _  _


### Number of attacks

1. First way

In [58]:
num_attacks(stochastic_local_search$xbest)

[1] 0

2. second way

In [59]:
stochastic_local_search$OFvalue

[1] 0

### Threshold Accepting

In [60]:
threshold_accepting_search <- TAopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                    printBar = T, nS = 10000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 31.3 secs

  Running Threshold Accepting ...
  Initial solution: 7 
  |============================================================| 100%
  Finished.
  Best solution overall: 1


### Initial positions of queens 

In [61]:
threshold_accepting_search$x0

[1] 2 2 2 2 2 2 2 2

### The best position for queens so that they don't attack each other

In [62]:
threshold_accepting_search$xbest

[1] 7 1 4 8 5 3 2 6

### Visualization of chess board

In [63]:
chessboard(threshold_accepting_search$xbest)

_  _  _  _  _  _  Q  _
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _
_  _  _  _  _  _  _  Q
_  _  _  _  Q  _  _  _
_  _  Q  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _


### Numbers of attacks

In [64]:
num_attacks(threshold_accepting_search$xbest)

[1] 1

In [65]:
threshold_accepting_search$OFvalue

[1] 1

### Simulated Annealing

In [67]:
simulated_annealing_search <- SAopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                    printBar = T, nS = 10000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 38.8 secs.

Running Simulated Annealing ...
Initial solution:  7 
  |======================================================================| 100%Finished.
Best solution overall: 0



## The best position for queens so they don't attack each other

In [68]:
simulated_annealing_search$xbest

[1] 5 3 1 7 2 8 6 4

### Visualization of chess board

In [69]:
chessboard(simulated_annealing_search$xbest)

_  _  _  _  Q  _  _  _
_  _  Q  _  _  _  _  _
Q  _  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  _  _  _  _  Q  _  _
_  _  _  Q  _  _  _  _


### Numbers of attacks

In [71]:
num_attacks(simulated_annealing_search$xbest)

[1] 0

In [72]:
simulated_annealing_search$OFvalue

[1] 0

In [74]:
?SAopt