### Solving N-queen problem with local search method

https://cran.r-project.org/web/packages/NMOF/index.html

In [98]:
install.packages("NMOF")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [1]:
library(NMOF)

#### Board Size

In [2]:
board_size <- 8

#### Just assuming the random position of the queens on the board ( taking a random solution)

In [3]:
pos <- sample.int(board_size)

pos

[1] 7 3 6 8 1 5 4 2

In [4]:
data.frame(row = 1:board_size, column=pos)

row column
1 1   7     
2 2   3     
3 3   6     
4 4   8     
5 5   1     
6 6   5     
7 7   4     
8 8   2

#### Function for visualizing position of queens on board

In [5]:
print_board <- function(position, q.char="1", sep = " ") {

    n <- length(position)
    row <- rep("*", n)

    for (i in seq_len(n)) {

         row_i <- row 
         row_i[position[i]] <- q.char

         cat(paste(row_i, collapse = sep))
         cat("\n")
    }   
}

In [6]:
print_board(pos)

* * * * * * 1 *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
1 * * * * * * *
* * * * 1 * * *
* * * 1 * * * *
* 1 * * * * * *


### Evaluating a solution

We need to compute on what row, column, diagonal (top left to bottom right) or reverse diagonal (top right
to bottom left) a queen stands. Rows and columns are simple. We label the diagonals as follows.

#### Initializing a null matrix with size N x N

In [7]:
board <- array(NA, dim=c(board_size, board_size))

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

##### Here we are taking reverse diagonal

In [8]:
for (row in 1:board_size)
    for (col in 1:board_size)
        
        board[row, col] <- col - row

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

In [9]:
board <- array(NA, dim=c(board_size, board_size))

for (row in 1:board_size)
    for (col in 1:board_size)
        
        board[row, col] <- col + row - (board_size + 1)

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] -7   -6   -5   -4   -3   -2   -1   0   
[2,] -6   -5   -4   -3   -2   -1    0   1   
[3,] -5   -4   -3   -2   -1    0    1   2   
[4,] -4   -3   -2   -1    0    1    2   3   
[5,] -3   -2   -1    0    1    2    3   4   
[6,] -2   -1    0    1    2    3    4   5   
[7,] -1    0    1    2    3    4    5   6   
[8,]  0    1    2    3    4    5    6   7

#### Function for counting attacks for a particular position 
#### For perfect solution the attacks should be zero

In [10]:
pos

[1] 7 3 6 8 1 5 4 2

In [11]:
duplicated(pos)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [12]:
seq_along(pos)

[1] 1 2 3 4 5 6 7 8

In [13]:
pos - seq_along(pos)

[1]  6  1  3  4 -4 -1 -3 -6

In [14]:
duplicated(pos - seq_along(pos))

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [15]:
sum(duplicated(pos - seq_along(pos)))

[1] 0

In [16]:
sum(duplicated(pos + seq_along(pos)))

[1] 1

In [17]:
n_attacks <- function(position) {
    sum(duplicated(position)) +
    sum(duplicated(position - seq_along(position))) +
    sum(duplicated(position + seq_along(position)))
}

In [18]:
n_attacks(pos)

[1] 1

### Changing a solution

A given position may be modified by picking one row randomly and then moving the queen there to the left
or right. We allow for moves up to step squares, which we set to 2 here.

In [20]:
neighbor <- function(position) {
    step <- 2
    i <- sample.int(board_size, 1)

    position[i] <- position[i] + sample(c(1:step, -(1:step)), 1)

    if (position[i] > board_size)
        position[i] <- 1
    else if (position[i] < 1)
        position[i] <- board_size

    position
}

#### Showing how the position of the queen is changing after calling neighbour function

In [21]:
print_board(pos)

* * * * * * 1 *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
1 * * * * * * *
* * * * 1 * * *
* * * 1 * * * *
* 1 * * * * * *


In [22]:
print_board(pos <- neighbor(pos))

* * * * * * 1 *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
1 * * * * * * *
* * * * 1 * * *
* * * 1 * * * *
* * * * * * * 1


In [23]:
print_board(pos <- neighbor(pos))

* * * * * * 1 *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
1 * * * * * * *
* * * * 1 * * *
* * 1 * * * * *
* * * * * * * 1


#### Setting the position of all the queen at 1 and then finding the best solution using the Local Search method

In [24]:
pos0 <- rep(1, board_size)

In [25]:
print_board(pos0)

1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *


### Simulated Annealing Method

In [26]:
solution <- SAopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 3.64 secs.

Running Simulated Annealing ...
Initial solution:  7 
  |======================================================================| 100%Finished.
Best solution overall: 0



In [27]:
solution$xbest

[1] 6 3 1 8 4 2 7 5

In [28]:
n_attacks(solution$xbest)

[1] 0

In [29]:
print_board(solution$xbest)

* * * * * 1 * *
* * 1 * * * * *
1 * * * * * * *
* * * * * * * 1
* * * 1 * * * *
* 1 * * * * * *
* * * * * * 1 *
* * * * 1 * * *


### Local Search Method

In [30]:
solution <- LSopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Local Search.
Initial solution:  7 
  |======================================================================| 100%
Finished.
Best solution overall: 1


In [31]:
n_attacks(solution$xbest)

[1] 1

In [32]:
print_board(solution$xbest)

* * 1 * * * * *
* * * * * 1 * *
* * 1 * * * * *
* * * * * * 1 *
* 1 * * * * * *
* * * 1 * * * *
* * * * * * * 1
1 * * * * * * *


### Threshold Accepting Method

In [33]:
solution <- TAopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 2.765 secs

  Running Threshold Accepting ...
  Initial solution: 7 
  |============================================================| 100%
  Finished.
  Best solution overall: 0


In [34]:
n_attacks(solution$xbest)

[1] 0

In [35]:
print_board(solution$xbest)

* * * * 1 * * *
1 * * * * * * *
* * * 1 * * * *
* * * * * 1 * *
* * * * * * * 1
* 1 * * * * * *
* * * * * * 1 *
* * 1 * * * * *


#### Previously we fixed the position of the queens on first position and then applying the Local Search method but this time we will take some random position and then apply the Local Search methods.

In [36]:
pos0 <- sample.int(board_size)

In [37]:
print_board(pos0)

* * * * * * * 1
* * * * * * 1 *
* * * 1 * * * *
* * * * 1 * * *
* * 1 * * * * *
1 * * * * * * *
* * * * * 1 * *
* 1 * * * * * *


In [38]:
solution <- SAopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 3.275 secs.

Running Simulated Annealing ...
Initial solution:  4 
  |======================================================================| 100%Finished.
Best solution overall: 0



In [39]:
n_attacks(solution$xbest)

[1] 0

In [40]:
print_board(solution$xbest)

* * * * 1 * * *
* * * * * * 1 *
* * * 1 * * * *
1 * * * * * * *
* * 1 * * * * *
* * * * * * * 1
* * * * * 1 * *
* 1 * * * * * *


In [41]:
solution <- LSopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Local Search.
Initial solution:  4 
  |======================================================================| 100%
Finished.
Best solution overall: 1


In [42]:
n_attacks(solution$xbest)

[1] 1

In [43]:
print_board(solution$xbest)

* * 1 * * * * *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
* * * * 1 * * *
1 * * * * * * *
* * * 1 * * * *
* * * * * * 1 *


In [44]:
solution <- TAopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 4.24 secs

  Running Threshold Accepting ...
  Initial solution: 4 
  |============================================================| 100%
  Finished.
  Best solution overall: 0


In [45]:
n_attacks(solution$xbest)

[1] 0

In [46]:
print_board(solution$xbest)

* 1 * * * * * *
* * * * * * 1 *
* * 1 * * * * *
* * * * * 1 * *
* * * * * * * 1
* * * * 1 * * *
1 * * * * * * *
* * * 1 * * * *


### Solving N-queens problem using function available in R

This function uses a direct transcript of Bo Bernhardsson's method.

https://www.rdocumentation.org/packages/magic/versions/1.5-9/topics/nqueens

https://dl.acm.org/citation.cfm?id=122319.122322

In [144]:
install.packages("magic")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [47]:
library(magic)

Loading required package: abind


In [48]:
bernhardsson(4)

[,1] [,2] [,3] [,4]
[1,] 0    1    0    0   
[2,] 0    0    0    0   
[3,] 1    0    0    0   
[4,] 0    0    1    0

In [49]:
bernhardsson(8)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0    0    0    1    0    0    0    0   
[2,] 0    0    0    0    0    1    0    0   
[3,] 0    0    0    0    0    0    0    0   
[4,] 0    1    0    0    0    0    0    0   
[5,] 0    0    0    0    0    0    1    0   
[6,] 1    0    0    0    0    0    0    0   
[7,] 0    0    1    0    0    0    0    0   
[8,] 0    0    0    0    1    0    0    0

In [50]:
bernhardsson(12)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,] 0    1    0    0    0    0    0    0    0    0     0     0    
 [2,] 0    0    0    1    0    0    0    0    0    0     0     0    
 [3,] 0    0    0    0    0    1    0    0    0    0     0     0    
 [4,] 0    0    0    0    0    0    0    1    0    0     0     0    
 [5,] 0    0    0    0    0    0    0    0    0    1     0     0    
 [6,] 0    0    0    0    0    0    0    0    0    0     0     1    
 [7,] 1    0    0    0    0    0    0    0    0    0     0     0    
 [8,] 0    0    1    0    0    0    0    0    0    0     0     0    
 [9,] 0    0    0    0    1    0    0    0    0    0     0     0    
[10,] 0    0    0    0    0    0    1    0    0    0     0     0    
[11,] 0    0    0    0    0    0    0    0    1    0     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     1     0